controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# 여기가 핵심! diff_drive_controller 설정을 별도 블록으로
diff_drive_controller:
  ros__parameters:

    use_stamped_vel: false

    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.32
    wheels_per_side: 2
    wheel_radius: 0.098

    odom_topic: odom

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 5.0
    linear.x.min_velocity: -5.0
    linear.x.max_acceleration: 5.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 5.0
    angular.z.min_velocity: -5.0
    angular.z.max_acceleration: 5.0

joint_state_broadcaster:
  ros__parameters: {}

arm_controller:
  ros__parameters:
    joints:
      - link2_to_link1
      - link3_to_link2
      - link4_to_link3
      - gripper_to_link4
      - gripper_left_joint
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0